### ISSUE TITLE
Torrents Not Being Displayed While Sorting

### ISSUE THREAD

**Issue by FelixGP** [NyaaPantsu/nyaa#624] opened 2017-05-19 02:53 UTC
It seems that when sorting by seeders or leechers, torrents that have no seeders or leechers (respectively) are not displayed. 
Search for Lostorage, English Translated; no sorting:
<img width="877" alt="vivaldi_2017-05-18_22-48-13" src="https://cloud.githubusercontent.com/assets/16271765/26231361/ca1285ca-3c1c-11e7-8ec9-a24093d850d7.png">
Search for Lostorage, English Translated; sorted by seeders
<img width="870" alt="vivaldi_2017-05-18_22-50-55" src="https://cloud.githubusercontent.com/assets/16271765/26231362/ca139546-3c1c-11e7-8614-057137b97fed.png">

**Comment by yiiTT** [comment] 2017-05-19 06:58
`SELECT * FROM torrents WHERE deleted_at IS NULL AND category = '3' AND sub_category = '5' AND seeders IS NOT NULL AND torrent_name LIKE '%Lostorage%' ORDER BY seeders desc LIMIT 50 OFFSET 0`

Looks like if there are no seeders it will not display them, this should be fixed.

**Comment by goonyaa** [comment] 2017-05-20 11:10
Was unable to reproduce it on latest dev, was it fixed already?

![image](https://cloud.githubusercontent.com/assets/892135/26275301/ec766d26-3d65-11e7-860e-3c9b3da9ec8e.png)

Queries look like this:
```sql
SELECT count(*) FROM "torrents"  WHERE (deleted_at IS NULL AND category = '3' AND sub_category = '5' AND torrent_name LIKE '%Lostorage%')
```
and
```sql
SELECT * FROM torrents WHERE deleted_at IS NULL AND category = '3' AND sub_category = '5' AND torrent_name LIKE '%Lostorage%' ORDER BY seeders desc LIMIT 50 OFFSET 0
```

**Comment by akuma06** [comment] 2017-05-20 13:10
It should be fixed in my previous commit

**Closed by akuma06** 2017-05-20 13:10 UTC
