### ISSUE TITLE
Random Language 

### ISSUE THREAD

**Issue by AnhDangSSS** [NyaaPantsu/nyaa#712] opened 2017-05-23 12:57 UTC
Default English but sometime have other language, better move list language above m(_ _)m

**Comment by akuma06** [comment] 2017-05-23 17:49
I don't quite get your problem, is it that when you navigate, sometimes the page is displayed in another language? Or is it that you have some elements in english and other in another language in the same page?
If you can provide a screenshot for the latter (if it is this), that would be helpful.

**Comment by AnhDangSSS** [comment] 2017-05-23 19:11
yes sometime page display another language very rare

**Comment by akuma06** [comment] 2017-05-23 19:13
@ElegantMonkey Has this been fixed?

**Comment by AnhDangSSS** [comment] 2017-05-23 19:16
fine rightnow hope not appear again 💃

**Comment by ElegantMonkey** [comment] 2017-05-23 19:55
@akuma06 @AnhDangSSS This is impossible to reproduce on a testing environment, and the only suspicious thing I got was a mixed translation page (half French, half Japanese I guess https://imgur.com/a/53FoA), which led me to pass the Tfunc as an argument instead of setting on the FuncMap (this build is already in production, if I'm not mistaken).

This case seems more like CloudFlare messing up with cache, as the page is entirely on Japanese, completely ignoring the Tfunc from the user request (the language shown on the selector is set from a JS function, on a separate request). IIRC CloudFlare will cache differently based on cookies, so, @AnhDangSSS, did you set the language on the language selector? And does this bug happens when you are logged in?

**Comment by AnhDangSSS** [comment] 2017-05-23 20:13
this bug only happen when i enter url link few times

**Comment by ElegantMonkey** [comment] 2017-05-23 20:21
@AnhDangSSS, so you mean that you won't get this bug by refreshing the page, only by inputting the URL? Also, please try manually setting your language on the selector at the bottom (even if you select English, pick another language and go back to English, it should at least set the lang cookie).

Is this only happening on Sukebei?

**Comment by ElegantMonkey** [comment] 2017-05-23 21:49
Ok, so I've used a [script](https://gist.github.com/ElegantMonkey/ac77abb91e58374499651a876aaca062) to access the site and parse the `lang` attribute from the `html` tag, and here are the results, after 1000 retries (I've run then in parallel, so that might have influenced a bit, but still):

- Sukebei + Accept-Language set to pt-br:
```
zh-tw, 1 times
it-it, 22 times
en-us, 8 times
zh-cn, 2 times
pt-br, 936 times
th-th, 1 times
fr-fr, 1 times
ja-jp, 29 times
```
- Sukebei + lang cookie set to "it-it", Accept-Language set to "pt-br":
```
it-it, 943 times
en-us, 8 times
ko-kr, 3 times
zh-cn, 1 times
pt-br, 20 times
fr-fr, 1 times
ja-jp, 24 times
```
- Nyaa + Accept-Language set to "pt-br":
```
pt-br, 1000 times
```
- Nyaa + lang cookie set to "it-it", Accept-Language set to "pt-br":
```
it-it, 1000 times
```
It seems that only Sukebei have the problem, so hopefully it will be fixed on a update.

**Comment by akuma06** [comment] 2017-05-23 22:19
Ok so sukebei is still not up to date =). Thanks for everything @ElegantMonkey!

**Comment by yiiTT** [comment] 2017-05-23 23:19
We should include the current build somewhere on the website to prevent wasted time on looking into issues that have already been resolved.

**Comment by egozi44** [comment] 2017-05-28 21:06
Still displayed it on other language than English here as well, and since it keep log me out after each time I close the browser it probably don't remember my settings

**Closed** 2017-05-31 10:49 UTC
Labels: bug, sukebei only

**Comment by egozi44** [comment] 2017-05-31 17:17
Why it been closed when it still happens to me on both sukebei and normal site? o_o

I got my home language rather than random language instead of English or numbers to the point in unreadable thanks to the fact the design not was build for such long words, please change it back to numbers only >.>

**Comment by akuma06** [comment] 2017-05-31 17:22
Not the same issue then egozi44, can you make another one with what is happening for you?

And try to see if it does the same on dev.pantsu.cat

**Comment by egozi44** [comment] 2017-05-31 17:24
Alright
