### ISSUE TITLE
Make theme switcher easier to spot

### ISSUE THREAD

**Issue by tomleb** [NyaaPantsu/nyaa#487] opened 2017-05-14 15:17 UTC
The theme switcher icon has to change, or something has to be done because there are still people that don't know that we have a dark theme.
Anyone got a suggestion ?

**Comment by Yamozer** [comment] 2017-05-14 21:15
Make the sun icon look more like a sun?

**Comment by autismbux** [comment] 2017-05-15 01:00
If the issue is that they blend in too well, then the opposite would be to make them stand out by using contrasting colors. I tried placing a button with dark theme colors in the day theme and vice versa with the night version. Also moved them to a more noticeable location just above the torrent list. Does this look better?

![daynight](https://cloud.githubusercontent.com/assets/28681516/26039372/4e8d239c-38e8-11e7-8c11-3d3b5ccd54de.jpg)

**Comment by Yamozer** [comment] 2017-05-15 19:07
I think it looks better.

**Comment by mitki** [comment] 2017-05-15 19:53
That's perfect.

**Comment by tomleb** [comment] 2017-05-15 20:02
What do you think about this ? [https://github.com/ewhal/nyaa/pull/411](https://github.com/ewhal/nyaa/pull/411) I put it in the navbar because they it is accessible everywhere on the site.
I'd like to replace the labels by the icons, where did you get the icons in your screenshot ?

**Comment by autismbux** [comment] 2017-05-16 00:30
You mean for the sun and moon? They're here: https://github.com/ewhal/nyaa/tree/dev/public/img

**Comment by tomleb** [comment] 2017-05-16 00:32
Yeah, I know but they're not black / dark, guess I could edit them in some way

**Comment by autismbux** [comment] 2017-05-16 00:41
Oh I see. What's the hex code for the "light/dark" text? I could help turning them into that color

**Comment by tomleb** [comment] 2017-05-16 00:59
The navbar color is #263238 and I believe the light text is #f2f2f2

**Comment by autismbux** [comment] 2017-05-16 01:15
Here you go https://mega.nz/#!QRFUlTiL!DkQxakJksFcPFrD06Y2e2J6QJCK39lIf--kTlH7U6Wg

**Comment by rschwiet** [comment] 2017-05-17 05:59
I had assumed the "sun" was a "gear" for settings, didn't know there was a dark theme

**Comment by kipukun** [comment] 2017-05-24 14:30
This is fixed with #723. Theme switcher is now a dropdown at the bottom of the page.

**Closed** 2017-05-26 19:49 UTC
Labels: enhancement, frontend
