### ISSUE TITLE
Javascript cleansing

### ISSUE THREAD

**Issue by tomleb** [NyaaPantsu/nyaa#384] opened 2017-05-12 04:47 UTC
Trying to reduce the use of js where only necessary
Functionality that does not work with JS:
- Member button
- Theme switcher (I don't think it matters if we use js for this)
- Torrent Size
- Date format in torrent view
- Advanced search button

**Comment by yiiTT** [comment] 2017-05-12 05:18
> Theme switcher (I don't think it matters if we use js for this)
A good amount of people suggested the theme switcher to be placed into the account settings and a cookie or similar.

**Comment by tomleb** [comment] 2017-05-12 05:35
What about user that don't want to use cookies ? But yeah, a couple of them wanted it in the account settings.

**Comment by ayame-git** [comment] 2017-05-12 07:23
Default theme in the account settings is a good idea

**Comment by ripdog** [comment] 2017-05-12 07:24
Eh, that removes theme switching for logged out users. Either that or we leave the current implementation in and end up with two.

The site works fine without JS. IMO leave it, because this is what JS was designed for - nice but unnecessary visual flair.

**Comment by kipukun** [comment] 2017-06-05 17:38
This is essentially fixed now. All things work without JS.

**Closed** 2017-06-06 21:21 UTC
Labels: bug, frontend
